### ISSUE TITLE
delimiter problem

### ISSUE THREAD

**Issue by bornTrade** [TimelordUK/jspurefix#13]
where can i add a delimiter between messages to avoid the msgs joining together like this:-

8=FIX.4.4|9=0000155|35=D|49=jspuretest|56=OURTEST|34=5|52=20210201-01:58:52.440|11=351365|1=16248|48=100|54=2|60=20210201-01:58:51.623|38=0.1|40=2|44=0.98765|59=3|10=058=FIX.4.4|

this causes an error in our receiver

**Comment by TimelordUK** [comment]
hello,

if you are connecting via a socket the messages are not sent with delimter | they are sent with standard fix SOH.  The receiver should not be receiving messages with | how are you sending them.  The delimeter is replaced on receiving side when receiving the message purely so it can viewed and read more easily.

in the demo application for example which has a client and server running in one node process the messages are sent by client with SOH standard FIX

**Comment by bornTrade** [comment]
hi, yes thank you, great 
amoi how do recieving engines know the length of each message i.e. 1=16248 versus 1=162489876  ? is it the next NN= used as delimiter?
