### ISSUE TITLE
Export statement issue on a custom types from a dictionary file

### ISSUE THREAD

**Issue by arthurradchenko** [TimelordUK/jspurefix#27]
Hey, I think, I've found a minor issue in "generate" script workflow. I have a custom dictionary file, and when I ran generate script, there is no index.ts in types/enum, but types/index.ts is referencing a file from types/enum
`export * from './enum'`, so I have to change this path manually to `export * from './enum/all-enum'`. I hope, I've give you all information about the issue.

**Comment by TimelordUK** [comment]
This should have been addressed in last build

**Comment by TimelordUK** [comment]
i think this is fixed closing
