### ISSUE TITLE
Non standard implementation of the FIX Protocol

### ISSUE THREAD

**Issue by aisfell** [TimelordUK/jspurefix#3]
Very nice library! I stumbled upon two issues when trying to connect to another implementation:

- BodyLength is calculated in jspurefix including the BeginString and the BodyLength and it should be without, please see: https://btobits.com/fixopaedia/fixdic44/index.html?tag_9_BodyLength.html . It might be different depending on the FIX version but its clearly wrong for FIX.4.4

- I'm not 100% sure your checksum calculation is correct but I'm very sure the tag is formed incorrcectly. It should always be exactly 3 characters with leading zeros and jspurefix encodes nubmers, e.g. 18 -> 18 but it should be 18 -> 018.

I have made these changes locally and it works fine now but would be nice to have this as part of a properly installed library.

**Comment by TimelordUK** [comment]
thanks a lot for pointing out these issues.  I will take a look and get these fixed.

**Comment by TimelordUK** [comment]
this should now be fixed with 1.14

**Comment by aisfell** [comment]
Thanks for the update. Is it just me or did about 50% of the tests for 'npm test' fail?

**Comment by TimelordUK** [comment]
Alll tests seem to pass on the cloud they get automatically rerun. I’ll
check again later today

**Comment by aisfell** [comment]
No hurry, try the https://github.com/TimelordUK/jspf-demo/ then you'll see what I'm talking about, or not... ;)

**Comment by aisfell** [comment]
The repo 'data/fix_repo.zip' did not unpack automatically, maybe an issue on my size. Anyhow, some jest tests might fail aswell but I can confirm that the body length and checksum are now correct. Thanks!
