### ISSUE TITLE
TLS should not require private key and cert

### ISSUE THREAD

**Issue by dave-fl** [TimelordUK/jspurefix#34]
Currently in order for a TLS connection to take place it is required that both a private key and cert be provided as part of the configuration description.  Neither of these are required in order to perform a successful TLS Connection and therefore TLS should be able to work with neither of these options being provided.

**Comment by TimelordUK** [comment]
Thanks for raising issue. I do t suppose you have a tested fix that works in this situation ideally a PR so I can test merge
