### ISSUE TITLE
Process crash if connection can't be made

### ISSUE THREAD

**Issue by hmvs** [TimelordUK/jspurefix#44]
The node process crashed if a socket connection can't be made. 

   Error: connect ETIMEDOUT 127.0.0.1:7001
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by TimelordUK** [comment]
There is a setting in application section of json which is a resilient book.  This will use recovering tcp initiation which does loop for a timeout period but even that eventually will stop after a period. This one will also attempt to reconnect if you lose tcp connection. I don’t know your exact requirement but this may help.

**Comment by hmvs** [comment]
Have a look in PR.

**Comment by hmvs** [comment]
Using `RecoveringTcpInitiator` actually solves the issue, however, I am losing control of retrying by myself. 
And I still believe `TcpInitiator` should not crash the app but should reject the Promise if it can't connect.

**Comment by hmvs** [comment]
I was wrong without the line in PR, the app crashes 

> 
> creating an application session with DI token FixSession. (module=StagingClient:RecoveringTcpInitiator)
> current state Idle (24) moves to DisconnectedNoConnectionToday (1) (module=StagingClient:FixSession)
> connect: start initiator timeout 60 (module=StagingClient:RecoveringTcpInitiator)
> current state DisconnectedNoConnectionToday (1) moves to InitiateConnection (5) (module=StagingClient:FixSession)
> connecting with timeout 60 (module=StagingClient:TcpInitiator)
> tryConnect stagingarea-ssl-int.360t.com:7001 (module=StagingClient:TcpInitiator)
> Error: connect ETIMEDOUT 127.0.0.1:7001
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
>   errno: -60,
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 7001
> }
> [nodemon] app crashed - waiting for file changes before starting...

**Comment by hmvs** [comment]
@TimelordUK thanks for the merging, however it requires more fixing. Looks like when connection timeout promise rejection is happening it is not handled properly, and the app crashes. 
I wanted to write a unit test on tcp-initiator however I haven't found an easy way.

**Comment by hmvs** [comment]
Hi @TimelordUK. I finally found the place which caused the app to crash. There was a mix of promise and async style and as a result, we had a lost promise there.  Have a look at #46

**Comment by hmvs** [comment]
@TimelordUK thank you for merging the PR. Any ideas when you plan to release a new version?

**Comment by TimelordUK** [comment]
done 2.1.0 - thanks for all your hard work in this.
