### ISSUE TITLE
IncorrectNumingroupCountForRepeatingGroup

### ISSUE THREAD

**Issue by bekee** [TimelordUK/jspurefix#48]
I'm facing an issue here.

My market data request keeps being rejected, I've every possible arrangements stills the same issue. 
The Fix server requires minimum of SecurityIDSource and SecurityID or  plus SecuritySubType

The sent request 
8=FIXT.1.1|9=0000124|35=V|49=RFL|56=XTRM|34=2|57=fix|52=20220826-08:54:47.439|262=test12356|263=1|264=1|265=1|266=Y|267=1|269=0|146=1|22=99|48=*|10=104|

Rejection message
```

2022-08-26T08:54:47.764Z [fundvine_client:FixSession] info: 3: Reject
0|fix  | 2022-08-26T08:54:47.765Z [fundvine_client:FixSession] info: [0] 8 (BeginString) = FIXT.1.1, [1] 9 (BodyLength) = 000123
0|fix  | [2] 35 (MsgType) = 3[Reject], [3] 49 (SenderCompID) = XTRM
0|fix  | [4] 56 (TargetCompID) = RFL, [5] 34 (MsgSeqNum) = 2
0|fix  | [6] 52 (SendingTime) = 20220826-08:54:47.607, [7] 45 (RefSeqNum) = 2
0|fix  | [8] 371 (RefTagID) = 146, [9] 372 (RefMsgType) = V
0|fix  | [10] 373 (SessionRejectReason) = 16[IncorrectNumingroupCountForRepeatingGroup], [11] 58 (Text) = Incorrect number in group count for tag 146
0|fix  | [12] 10 (CheckSum) = 233
0|fix  | 2022-08-26T08:54:47.766Z [fundvine_client:FixSession] info: peer rejects type '3' with text 'Incorrect number in group count for tag 146'
```

I'm not sure what I'm doing wrong
@TimelordUK

**Comment by TimelordUK** [comment]
Who is vendor. Are you sure the request contains the required fields you are expected to send they often add their own fields which need to be added to the data dictionary. Did they provide an example message or any documentation at all

**Comment by bekee** [comment]
I've sorted the issue

For anyone facing this issue, they should look at how the vendor wants the repeating groups to be ordered
