### ISSUE TITLE
BeginString Tag 8 should be 8=FIX.4.x rather than 8=FIX4.x etc

### ISSUE THREAD

**Issue by NikolaosWakem** [TimelordUK/jspurefix#50]
There should be an extra . in the BeginString in the examples etc

e.g. 8=FIX.4.x rather than 8=FIX4.x etc

otherwise lots of headaches ;-)

**Comment by TimelordUK** [comment]
thanks for raising this.  I have partially fixed this with config and some tests - some of tests will be quite time consuming to fix as  we are checking exact buffer positions which would all fail.

**Comment by TimelordUK** [comment]
closing this now fixed thanks for raising issue
